config/routes.rb
Rails.application.routes.draw do
  get 'add_visitor/event_registration'
  resources :events
  devise_for :users
  root :to => 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/profile'
  get 'static_pages/user_events'
  get 'static_pages/user_visitor'
  get 'static_pages/about'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :user
    has_many :visitors, dependent: :destroy

    validates :start_date,
          date: { after: Proc.new { Time.now } }

    validates :end_date,
            date: { after: :start_date }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, dependent: :destroy
end

app/models/visitor.rb
class Visitor < ApplicationRecord
    belongs_to :event
    validates :event_id, uniqueness: { scope: :user_id }, presence: true
    validates :user_id, presence: true
end

app/controllers/add_visitor_controller.rb
# frozen_string_literal: true

# Controller class for Visitor model usage
class AddVisitorController < ApplicationController
  before_action :authenticate_user!, raise: false

  def event_registration
    if Visitor.find_by(user_id: current_user.id, event_id: params[:event_id]).nil?
      @visitor = Visitor.new(user_id: current_user.id, event_id: params[:event_id])
      @visitor.save

      @error = false
    else
      @error = true
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Main controller
class ApplicationController < ActionController::Base
  before_action :set_locale
  @@prev_locale = 'ru'

  def set_locale
    if params[:locale]
      I18n.locale = params[:locale]
      @@prev_locale = params[:locale]
    else
      I18n.locale = @@prev_locale
    end
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

# Controller for Events model application
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new show edit update destroy]
  before_action :access?, only: %i[show edit update destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @visitors = Visitor.where(event_id: params[:id])
    @user_emails = @visitors.map do |visitor|
      User.find_by(id: visitor.user_id).email
    end
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user = current_user

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: t(:'Event was successfully created') }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: t(:'Event was successfully updated') }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: t(:'Event was successfully destroyed') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:name, :start_date, :end_date, :description)
  end

  def access?
    return if current_user.id == @event.user_id

    respond_to do |format|
      format.html { redirect_to events_url, notice: t(:'You do not have access to this event') }
    end
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

# Controller class for not-model pages
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: %i[profile user_events user_visitor], raise: false

  def home; end

  def about; end

  def profile
    @user = current_user
  end

  def user_events
    @events = Event.where(user_id: current_user.id)
  end

  def user_visitor
    user_as_visitor = Visitor.where(user_id: current_user.id)
    @events = user_as_visitor.map do |visitor|
      Event.find_by(id: visitor.event_id)
    end
  end
end

app/helpers/add_visitor_helper.rb
module AddVisitorHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/add_visitor/event_registration.html.erb
 <% unless @error %>
    <h1><%= t(:'Thank you for registration') %>!</h1>
 <% else %>
    <h1 class="error"> <%= t(:'User with this email is already registered') %>. </h1>
 <% end %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(@event.errors.count, "error") %> <%= t(:'prohibited this event from being saved') %>:</p>
      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="form-group col-md-4">
      <%= f.label :name, (t(:'Name'))%><br>
      <%= f.text_field :name, class: "form-control", required: true %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-4">
      <%= f.label :start_date, (t(:'Event starts (GMT+3 Moscow)')) %><br>
      <%= f.datetime_field :start_date, 
                        min: Date.today,
                        class: "form-contol",
                        required: true %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-4">
      <%= f.label :end_date, (t(:'Event ends (GMT+3 Moscow)')) %><br>
      <%= f.datetime_field :end_date, 
                        min: Date.today,
                        class: "form-contol",
                        required: true %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-4">
      <%= f.label :description, (t(:'Description')) %><br>
      <%= f.text_area :description, class: "form-control", required: true %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit (t(:'Create')), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1><%= t(:'Editing event') %></h1>

<%= render 'form', event: @event %>

<div class="edit-block">
<%= link_to (t(:'Show')), @event, class: "btn btn-warning" %>
</div>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>
<h2 class="mb-4"><%= t(:'Events list') %></h2>
<div class="event-block">
   <% Array(@events).each do |event| %>
      <div class="card mb-5">
        <div class="card-header">
          <%= t(:'by') %> <%= event.user.email %>
        </div>
        <div class="card-body">
          <h5 class="card-title"> <%= event.name %></h5>
        </div>
        <div class="card-body">
          <p><%= t(:'Starts') %>: <%= event.start_date.strftime('%d.%m.%Y %H:%M') %></p>
          <hr>
          <p><%= t(:'Ends') %>: <%= event.end_date.strftime('%d.%m.%Y %H:%M') %></p>
          <hr>
          <p><%= event.description %></p>
        </div>
        <div class="card-body">
            <%= link_to (t(:'I will go!')), {"controller"=>"add_visitor", "action"=>"event_registration", event_id: event.id}, class: "btn btn-info"%>
        </div>
      </div>
  <% end %>
</div>
<br>
<% if user_signed_in? %>
<%= link_to (t(:'New event')), new_event_path, class: "btn btn-primary" %>
<% end %>

app/views/events/new.html.erb
<h1><%= t(:'New event') %></h1>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t(:'Event') %></h1>
<p>
  <strong><%= t(:'Name') %>:</strong>
  <%= @event.name %>
</p>

<p>
  <strong><%= t(:'Event starts (GMT+3 Moscow)') %>:</strong>
  <%= @event.start_date.strftime('%m.%d.%Y %H:%M') %>
</p>

<p>
  <strong><%= t(:'Event ends (GMT+3 Moscow)') %>:</strong>
  <%= @event.end_date.strftime('%m.%d.%Y %H:%M') %>
</p>

<p>
  <strong><%= t(:'Description') %>:</strong>
  <%= @event.description %>
</p>

<p>
  <strong><%= t(:'Visitors') %>:</strong>
  <% @user_emails.each do |user_email| %>
    <p><%= user_email %></p>
  <% end %>
</p>
<% if @event.user_id == current_user %>
  <%= link_to (t(:'Edit')), edit_event_path(@event), class: "btn btn-warning"  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="h-100">
  <head>
    <title>Final</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha256-98vAGjEDGN79TjHkYWVD4s87rvWkdWLHPs5MC3FvFX4=" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <link href="https://getbootstrap.com/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

  </head>
  <body>
  <div class="special-wrapper">
      <header>
      <nav class="navbar navbar-expand-lg  navbar-dark bg-dark fixed-top nav-masthead float-md-end">
        <%= link_to "Tonight!", root_path, class:"navbar-brand  masthead-brand mr-auto" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse navbar-collapse-special" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item <%= 'active' if current_page?(root_path) %>">
              <%= link_to (t(:'Home')), root_path, class:"nav-link" %>
            </li>
            <li class="dropdown <%= 'active' if current_page?(events_path) or current_page?(new_event_path) or current_page?('/static_pages/user_events/') %>">
              <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <%= t(:'Events') %>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><%= link_to (t(:'All events')), events_path, class:"dropdown-item" %></li>
                <% if user_signed_in? %>
                <li><%= link_to (t(:'Created events')), '/static_pages/user_events/', class:"dropdown-item" %></li>
                <li><%= link_to (t(:'New event')), new_event_path, class:"dropdown-item" %></li>
                 <% end %>
              </ul>
            </li>
            <li class="nav-item <%= 'active' if current_page?("/static_pages/about") %>">
              <%= link_to (t(:'About')), "/static_pages/about", class:"nav-link" %>
            </li>
            <li class="dropdown <%= 'active' if current_page?("/static_pages/profile") or current_page?(new_user_registration_path) or current_page?(new_user_session_path) %>">
              <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <%= t(:'Profile') %>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <% if user_signed_in? %>
                <li><%= link_to (t(:'My profile')), "/static_pages/profile", class:"dropdown-item" %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to (t(:'Logout')), destroy_user_session_path, method: :delete, class:"dropdown-item" %></li>
                <% else %>
                <li><%= link_to (t(:'Sign up')), new_user_registration_path, class:"dropdown-item" %></li>
                <li><%= link_to (t(:'Log in')), new_user_session_path, class:"dropdown-item" %></li>
                <% end %>
              </ul>
            </li>
            <li class="nav-item">
              <% if I18n.locale == :ru %>
                <%= link_to "English version", { :locale=>'en' }, class:"nav-link" %>
              <% else %>
                <%= link_to "Русская версия", { :locale=>'ru' }, class:"nav-link" %>
              <%end%>
            </li>
          </ul>
        </div>
      </nav>
      </header>
    
    <div class="d-flex w-100 h-100 p-3 mx-auto flex-column">
      <main class="px-3">   

        <%= yield %>
      </main>
    </div>

    <footer class="bg-dark mt-auto">
        <div class="footer-container">
          <span>Tonight! &#169; 2020</span>
        </div>
    </footer>
        </div>
    
  </body>
</html>

app/views/static_pages/about.html.erb
<div class="col-sm-10 mx-auto">
    <div class="card mx-auto text-center w-100 h-100">
    <div class="notice"><%= notice %></div>
    <div class="alert error"><%= alert %></div>
    <h1 class="card-title"><%= t(:'About') %></h1>
    <p class="lead">
        <%= t(:'This is an educational Ruby on Rails project') %>, 
        <%= t(:'carried out on the course') %> 
        "<%= t(:'Internet Programming Languages') %>" 
        <%= t(:'by Anna Bushe, a student of the IU6-31B group') %>.
    </p>
    </div>
</div>

app/views/static_pages/home.html.erb
<div class="col-sm-10 mx-auto">
    <div class="card mx-auto text-center w-100 h-100">
    <div class="notice"><%= notice %></div>
    <div class="alert error"><%= alert %></div>
    <h1 class="card-title display-1">Tonight!</h1>
    <h2 class="mb-4"> <%= t(:'All events in one place') %></h2>
    <p class="lead">
    <% if user_signed_in? %>
         <%= link_to (t(:'To events')), events_path, class:"btn btn-lg btn-dark" %>
    <% else %>
        <%= link_to (t(:'Get started')), new_user_session_path, class:"btn btn-lg btn-dark" %>
    <% end %>
    </p>
    </div>
</div>

app/views/static_pages/profile.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4"><%= t(:'Profile') %></h1>
    <p class="lead">Email: <%=  @user.email %></p>
    <div class="profile-button-block">
        <%= link_to (t(:'Edit profile')), edit_user_registration_path, class: "btn btn-primary btn-lg profile-button" %>
    </div>
    <div class="profile-button-block">
        <%= link_to (t(:'Logout')), destroy_user_session_path, method: :delete, class: "btn btn-primary btn-lg profile-button" %>
    </div>
    <div class="profile-button-block">
        <%= link_to (t(:'Created events')), '../static_pages/user_events/', class: "btn btn-info btn-lg profile-button" %>
    </div>
    <div class="profile-button-block">
        <%= link_to (t(:'My events')), '../static_pages/user_visitor/', class: "btn btn-primary btn-lg profile-button" %>
    </div>
  </div>
</div>

app/views/static_pages/user_events.html.erb
<p id="notice"><%= notice %></p>
<h2 class="mb-4"><%= t(:'Created events') %></h2>
<div class="event-block">
  <% Array(@events).each do |event| %>
      <div class="card mb-5">
        <div class="card-header">
          <%= t(:'by') %> <%= event.user.email %>
        </div>
        <div class="card-body">
          <h5 class="card-title"> <%= event.name %></h5>
        </div>
        <div class="card-body">
          <p><%= t(:'Starts') %>: <%= event.start_date.strftime('%d.%m.%Y %H:%M') %></p>
          <hr>
          <p><%= t(:'Ends') %>: <%= event.end_date.strftime('%d.%m.%Y %H:%M') %></p>
          <hr>
          <div class="intro_inner">
            <div class="press btn btn-outline-primary mb-4"><%= t(:'Description') %></div>
            <div class="hidden_text"><%= event.description %></div>
          </div>
        </div>
        <div class="card-body">
          <%= link_to (t(:'Show')), event_path(event), class: "btn btn-info" %>
          <%= link_to (t(:'Edit')), edit_event_path(event), class: "btn  btn-warning" %>
          <%= link_to (t(:'Destroy')), event_path(event), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </div>
      </div>
  <% end %>
</div>
<%= link_to (t(:'New event')), new_event_path, class: "btn btn-lg btn-info mt-auto" %>
</div>
<br>

<script>
[...document.querySelectorAll('.press')].forEach(btn => {
  btn.addEventListener('click', function() {
    if (this.parentNode.style.height == '120px') {
      this.parentNode.children[1].style.height = '0px';
      this.parentNode.style.height = '20px';
    }
    else {
      this.parentNode.children[1].style.height = '80px';
      this.parentNode.style.height = '120px';
    }

  })
});
</script>

app/views/static_pages/user_visitor.html.erb
<p id="notice"><%= notice %></p>
<h2 class="mb-4"><%= t(:'My events') %></h2>
<div class="event-block">
  <% Array(@events).each do |event| %>
      <div class="card mb-5">
        <div class="card-header">
          <%= t(:'by') %> <%= event.user.email %>
        </div>
        <div class="card-body">
          <h5 class="card-title"> <%= event.name %></h5>
        </div>
        <div class="card-body">
          <p><%= t(:'Starts') %>: <%= event.start_date.strftime('%d.%m.%Y %H:%M') %></p>
          <hr>
          <p><%= t(:'Ends') %>: <%= event.end_date.strftime('%d.%m.%Y %H:%M') %></p>
          <hr>
          <div class="intro_inner mb-4">
            <div class="press btn btn-outline-primary mb-4"><%= t(:'Description') %></div>
            <div class="hidden_text"><%= event.description %></div>
          </div>
        </div>
      </div>
  <% end %>
<br>

<script>
[...document.querySelectorAll('.press')].forEach(btn => {
  btn.addEventListener('click', function() {
    if (this.parentNode.style.height == '120px') {
      this.parentNode.children[1].style.height = '0px';
      this.parentNode.style.height = '20px';
    }
    else {
      this.parentNode.children[1].style.height = '80px';
      this.parentNode.style.height = '120px';
    }

  })
});
</script>